JWT_SECRET_KEY="super-secret"
AWS_REGION_NAME="us-east-1"
AWS_ACCESS_KEY_ID="foo"
AWS_SECRET_ACCESS_KEY="foo"
AWS_ENDPOINT_URL="http://localhost.localstack.cloud:4566"
AWS_QUEUE_URL="http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/maps-uploaded"
