version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "80:5000"
    depends_on:
      - localstack
    volumes:
      - .:/app

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sqs
    volumes:
      - ./localstack/ready.d:/etc/localstack/init/ready.d
