version: '3'

services:
  app:
    build:
      context: .
    environment:
      - CONFIG=config.py
    depends_on:
      - localstack
    volumes:
      - .:/app
    network_mode: "host"        

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb,sqs
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
    volumes:
      - ./localstack/ready.d:/etc/localstack/init/ready.d
    network_mode: "host"        
